### ISSUE TITLE
java.lang.IllegalStateException when using Seq.sorted() with other operations

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOL#189]
This is a jOOL 0.9.9 regression. The following code:

```java
Seq.of("a", "b")
        .sorted()
        .zipWithIndex()
        .toList();
```

Causes

```
Exception in thread "main" java.lang.IllegalStateException
	at java.util.Spliterator.getComparator(Spliterator.java:465)
	at java.util.stream.StreamOpFlag.fromCharacteristics(StreamOpFlag.java:734)
	at java.util.stream.StreamSupport.stream(StreamSupport.java:70)
	at org.jooq.lambda.Seq.seq(Seq.java:2440)
	at org.jooq.lambda.SeqUtils.transform(SeqUtils.java:56)
	at org.jooq.lambda.Seq.zipWithIndex(Seq.java:4252)
	at org.jooq.lambda.Seq.zipWithIndex(Seq.java:898)
	at com.company.Main.main(Main.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

This is a regression caused by https://github.com/jOOQ/jOOL/issues/144

**Comment by amaembo** [comment]
Just took a look what's going on on the enemy base :-) Seems that you're pretty new to spliterators. Let me break your code:

	Seq.of(1,2,3).filter(x -> true).sorted().cycle(3).sorted().forEach(System.out::println);

Output:

    1
    2
    3
    1
    2
    3
    1
    2
    3

Huh? Where's my sorting?

	Seq.of(1,2,3).filter(x -> true).sorted(Comparator.naturalOrder()).cycle(3).sorted().forEach(System.out::println);

Output:

    1
    1
    1
    2
    2
    2
    3
    3
    3
    
Hey, now it's ok!

You might wonder, why I needed this `.filter(x -> true)`? Let's try without:

	Seq.of(1,2,3).sorted(Comparator.naturalOrder()).cycle(3).sorted().forEach(System.out::println);

Ka-boom!

    Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 3
	at java.util.stream.SortedOps$SizedRefSortingSink.accept(SortedOps.java:362)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at org.jooq.lambda.Seq.lambda$cycle$423(Seq.java:2689)
	at org.jooq.lambda.Seq$$Lambda$1/1595428806.tryAdvance(Unknown Source)
	at org.jooq.lambda.SeqUtils$1.tryAdvance(SeqUtils.java:60)
	at java.util.Spliterator.forEachRemaining(Spliterator.java:326)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.jooq.lambda.SeqImpl.forEach(SeqImpl.java:147)
	at BreakJool.main(BreakJool.java:9)

**Comment by lukaseder** [comment]
Huh, indeed - thanks very much for reporting!
