### ISSUE TITLE
UnsupportedClassVersionError after upgrade to 0.9.14 Java 9+ required

### ISSUE THREAD

**Issue by novaterata** [jOOQ/jOOL#339]
I upgraded jool from 0.9.12 to 0.9.14 and now I'm seeing a warning implying I need to be using JDK9+ if I want to use a Seq. That can't be right can it?
```
Caused by: java.lang.UnsupportedClassVersionError: org/jooq/lambda/Seq has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
```

### Versions:

- jOOλ: 0.9.14
- Java: 1.8.0_121

**Comment by novaterata** [comment]
Nevermind! Just saw that you split the artifacts

**Comment by billoneil** [comment]
See https://github.com/jOOQ/jOOL#download

```xml
<dependency>
  <groupId>org.jooq</groupId>
  <artifactId>jool-java-8</artifactId>
  <version>0.9.13</version>
</dependency>
```
